### ISSUE TITLE
getaddrinfo: nodename nor servname provided

### ISSUE THREAD

**Issue by clong** [josenk/vagrant-vmware-esxi#17] opened 2018-02-23 08:36 UTC
Hi there,

Thanks so much for working on this plugin, it's really excellent work and very considerate of you to continue updating it. 

I'm attempting to bring up an Ubuntu box and the transfer works successfully, but after `Waiting for state "running"` I get a crash:
```
/Users/clong/.vagrant.d/gems/2.4.2/gems/vagrant-vmware-esxi-2.0.2/lib/vagrant-vmware-esxi/action/read_state.rb:24:in `getaddrinfo': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/clong/.vagrant.d/gems/2.4.2/gems/vagrant-vmware-esxi-2.0.2/lib/vagrant-vmware-esxi/action/read_state.rb:24:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/clong/.vagrant.d/gems/2.4.2/gems/vagrant-vmware-esxi-2.0.2/lib/vagrant-vmware-esxi/action/read_ssh_info.rb:16:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/clong/.vagrant.d/gems/2.4.2/gems/vagrant-vmware-esxi-2.0.2/lib/vagrant-vmware-esxi/action/esxi_password.rb:18:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:227:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:202:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/environment.rb:600:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:188:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:188:in `action'
	from /Users/clong/.vagrant.d/gems/2.4.2/gems/vagrant-vmware-esxi-2.0.2/lib/vagrant-vmware-esxi/provider.rb:24:in `state'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:514:in `state'
	from /Users/clong/.vagrant.d/gems/2.4.2/gems/vagrant-vmware-esxi-2.0.2/lib/vagrant-vmware-esxi/action/wait_for_state.rb:27:in `block in call'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:33:in `catch'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:33:in `catch'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
	from /Users/clong/.vagrant.d/gems/2.4.2/gems/vagrant-vmware-esxi-2.0.2/lib/vagrant-vmware-esxi/action/wait_for_state.rb:26:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/call.rb:43:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/clong/.vagrant.d/gems/2.4.2/gems/vagrant-vmware-esxi-2.0.2/lib/vagrant-vmware-esxi/action/boot.rb:16:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/clong/.vagrant.d/gems/2.4.2/gems/vagrant-vmware-esxi-2.0.2/lib/vagrant-vmware-esxi/action/read_state.rb:29:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/clong/.vagrant.d/gems/2.4.2/gems/vagrant-vmware-esxi-2.0.2/lib/vagrant-vmware-esxi/action/createvm.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/clong/.vagrant.d/gems/2.4.2/gems/vagrant-vmware-esxi-2.0.2/lib/vagrant-vmware-esxi/action/read_state.rb:29:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/clong/.vagrant.d/gems/2.4.2/gems/vagrant-vmware-esxi-2.0.2/lib/vagrant-vmware-esxi/action/esxi_password.rb:18:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:227:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:202:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/environment.rb:631:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:188:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:188:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
	from /opt/vagrant/embedded/gems/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

Here's my sample Vagrantfile:
```
Vagrant.configure("2") do |config|

  config.vm.define "logger" do |cfg|
    cfg.vm.box = "bento/ubuntu-16.04"
    cfg.vm.hostname = "logger"
    config.vm.provision :shell, path: "bootstrap.sh"
    cfg.vm.network :private_network, ip: "192.168.38.5", gateway: "192.168.38.1", dns: "8.8.8.8"

    cfg.vm.provider "vmware_fusion" do |v, override|
      v.memory = 2048
      v.cpus = 1
      v.gui = true
    end

    cfg.vm.provider "vmware_esxi" do |esxi, override|
      esxi.guest_numvcpus = '2'
      esxi.guest_memsize = '2048'
      esxi.esxi_hostname = '192.168.3.105'
      esxi.esxi_password = "env:esxi_password"
      esxi.esxi_virtual_network = ['NAT Network','VM Network 3']
      esxi.guest_name = 'logger'
    end

    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.customize ["modifyvm", :id, "--cpus", 1]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end
end
```

**Comment by clong** [comment] 2018-02-23 08:52
Ah, it looks like I may be running into this: https://github.com/copiousfreetime/torid/issues/2

If I hardcode the correct IP address in that statement, everything continues as expected.

**Comment by josenk** [comment] 2018-02-23 14:46
Interesting...  I have not seen this issue before.    I don't fully understand what caused it and even if you resolved it???   Which IP did you hardcode?   The esxi host or guest IP?

Have you figured out root cause?    Is there a way I can re-create the issue?  Please set "esxi.debug = 'true ip' to enable ip debugging.

Also, I'm just about to release an updated plugin that does IP guest caching to speed things up...   Could you test it out and let me know if it gives the same results, or fixes it, or makes it worse.

# wget https://dc002.jintegrate.co/73748439276449/vagrant-vmware-esxi-2.0.4.gem

**Comment by clong** [comment] 2018-02-24 18:23
Hi @josenk,

Sorry for the sparse data in my issue, I was doing late night debugging. The problem appears to be line  24 in [read_state.rb.](https://github.com/josenk/vagrant-vmware-esxi/blob/master/lib/vagrant-vmware-esxi/action/read_state.rb#L24)

That command fails on default ruby installations of OSX Sierra:
```
irb(main):001:0> require 'socket'
=> true
irb(main):002:0> Socket::getaddrinfo(Socket.gethostname,"echo",Socket::AF_INET)
SocketError: getaddrinfo: nodename nor servname provided, or not known
	from (irb):2:in `getaddrinfo'
	from (irb):2
	from /usr/bin/irb:12:in `<main>'
irb(main):003:0>
```

However, I'm not very familiar with Ruby, so it's entirely possible that I'm missing something. If I change `Socket.gethostname` to my IP address (i.e. `Socket::getaddrinfo('192.168.1.10',"echo",Socket::AF_INET)`) then everything seems to work fine.

**Comment by josenk** [comment] 2018-02-25 03:26
Which of these three commands give the correct IP of your system?

ruby -rsocket -e 'puts Socket::getaddrinfo(Socket.gethostbyname(Socket.gethostname).first,"echo",Socket::AF_INET)[0][3]'

ruby -rsocket -e 'puts IPSocket.getaddress(Socket.gethostname)'

ruby -rsocket -e 'puts IPSocket.getaddress(Socket.gethostbyname(Socket.gethostname).first)'

**Comment by clong** [comment] 2018-02-26 06:46
I made a very interesting discovery around this tonight. All 3 of those commands succeed if I only have a single network adapter connected, but I typically have both Wifi and a USB ethernet adapter connected at the same time. 

When I only use wifi (leaving USB disconnected), all 3 commands work successfully. 
```
$ ruby -rsocket -e 'puts IPSocket.getaddress(Socket.gethostbyname(Socket.gethostname).first)'
192.168.1.21
$ ruby -rsocket -e 'puts Socket::getaddrinfo(Socket.gethostbyname(Socket.gethostname).first,"echo",Socket::AF_INET)[0][3]'
192.168.1.21
$ ruby -rsocket -e 'puts IPSocket.getaddress(Socket.gethostname)'
192.168.1.21
```

However, once I plugin the USB adapter, I receive the following:
```
$ ruby -rsocket -e 'puts IPSocket.getaddress(Socket.gethostbyname(Socket.gethostname).first)'
-e:1:in `gethostbyname': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from -e:1:in `<main>'
$ ruby -rsocket -e 'puts Socket::getaddrinfo(Socket.gethostbyname(Socket.gethostname).first,"echo",Socket::AF_INET)[0][3]'
-e:1:in `gethostbyname': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from -e:1:in `<main>'
$ ruby -rsocket -e 'puts IPSocket.getaddress(Socket.gethostname)'
-e:1:in `getaddress': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from -e:1:in `<main>'
```

So it appears that maybe this code only supports systems with a single network interface (at least on MacOS)?

**Comment by josenk** [comment] 2018-02-26 14:41
Damn,  I was hoping I could use one of those to get the IP on a Mac.   Try this one.

ruby -rsocket -e 'puts Socket.ip_address_list[1].ip_address'

**Comment by clong** [comment] 2018-02-27 20:29
Ah unfortunately that just returns the IPV6 address for loopback :(

```
$ ruby -rsocket -e 'puts Socket.ip_address_list[1].ip_address'
::1
```

**Comment by josenk** [comment] 2018-02-28 19:07
Should be fixed in V2.0.5.  Please test and let me know how it works out.

**Comment by clong** [comment] 2018-03-01 18:18
Hey @josenk - I would say this is fixed well enough. In some cases it's sub-optimal to assume that the first IP address is going to be the one you want to use for the NFS host, but the only way I could see to work around this would be to prompt the user and ask them which IP address to use. Thanks for addressing this!

**Comment by josenk** [comment] 2018-03-01 18:30
Yea, I agree.  

But remember...  The real problem is:   The ruby module that should get the IP address on a certain version of Mac crashes.   That is not exactly my problem...   Once that is resolved, developers like me won't need to do work-arounds for other peoples bugs in their code.   Sorry for my rant.  :-)

**Closed by josenk** 2018-03-01 18:30 UTC

**Comment by copiousfreetime** [comment] 2018-03-22 22:06
@josenk @clong if you go down to the C level this also happens, basically on modern macs, the hostname returned from `gethostname()` is not guaranteed to be usable as the hostname parameter to `getaddrinfo()` or the host parameter to `gethostbyname()`Here's example C code to test out on your various machines and see if that is true - https://gist.github.com/copiousfreetime/44a950fb0fa8896450af75f919dbe7f1

**Comment by josenk** [comment] 2018-03-23 01:42
Good information to know.   
    You would think name resolution should be easy...   It's often not.
