### ISSUE TITLE
Detection Lab with ESXi

### ISSUE THREAD

**Issue by Dviros** [josenk/vagrant-vmware-esxi#85] opened 2019-04-13 09:33 UTC
Dear @josenk,
Thanks a lot for your plugin.

We have been trying to import Detection Lab ( https://github.com/clong/DetectionLab ) to ESXi as it currently support only Fusion, VirtualBox and VMware Workstation.
As part of this support I've been using your plugin and created the following Pull Request (https://github.com/clong/DetectionLab/pull/234 ), but we were facing several issues related to the code of the plugin (  https://github.com/josenk/vagrant-vmware-esxi/blob/master/lib/vagrant-vmware-esxi/action/read_ssh_info.rb#L56-L79 ) in a way that didn't allowed us to communicate properly with the machines, especially when using SMB and WinRM. 
Can you please help us to solve it?

Thanks again!

**Comment by josenk** [comment] 2019-04-13 13:34
Looks like your running into a problem similar to this...
>https://github.com/josenk/vagrant-vmware-esxi/issues/20

Trying to get a callback to your pc/laptop for nfs/smb is almost impossible.   There is no easy way to know 1000% what is the correct ip to send to the new guest.   

It's much easier for vmware workstation because it's in a controlled subnet.    The esxi host network is not controlled by the plugin...

rsync should work perfectly well, or maybe as part of your provisioning you can connect to a 'known' smb server.

**Comment by Dviros** [comment] 2019-04-14 16:36
Hey @josenk, much appreciated.
Will contact clong and check it further.
Can we keep this issue opened in the meanwhile?
Thanks again.

**Comment by clong** [comment] 2019-04-18 01:55
Hey @josenk,

I don't know if this issue actually has anything to do with SMB/NFS. Consider the following example:

I'm provisioning a host with 3 interfaces on 3 different virtual networks
Network1 address: 10.0.0.1
Network2 address: 172.16.0.1
Network3 address: 192.168.0.1

Let's say the machine I'm running this from has an IP address of `192.168.0.2` - the only interface I would successfully be able to connect to using WinRM is 192.168.0.1 on Network3. However, the code outlined here seems to somewhat arbitrarily choose one: https://github.com/josenk/vagrant-vmware-esxi/blob/master/lib/vagrant-vmware-esxi/action/read_ssh_info.rb#L56-L79

Is there some sort of way it could loop through all available address and attempt a ping/TCP connection to see which interfaces are actually reachable before trying to continue?

I had a similar problem with stock Vagrant here and setting `enable_vmrun_ip_lookup = false` fixed the problem, although to this day I have no idea why: https://github.com/hashicorp/vagrant/issues/9949

**Comment by josenk** [comment] 2019-04-24 13:10
The way NFS/SMB is implemented in Vagrant was designed for environments like VirtualBox, VMware workstation, or some other local type of virtualization.  It can work reliably because its in a controlled environment.   The implementation I'm doing will work in a simple environment.  (multiple interfaces, non-standard dns resolution, wifi interfaces all makes things complicated).   To try to implement it when nothing can be considered reliable or secure and to try to make it work for every configuration will just have too many corner cases and will be hackey at best.   (I already try two different methods to figure out the best interface to use)

The method used to determine your local IP is not arbitrarily and is documented on. 
https://github.com/josenk/vagrant-vmware-esxi/blob/59c3f05c691c3d9daabab726c5254c3ed87eb273/lib/vagrant-vmware-esxi/action/read_state.rb#L28-L35

  Using your suggestion.  Just cycle through and ping through each address...  There's a few issues with that.
     1) I have multiple interfaces on my laptop.  They all ping my esxi host (you noticed I didn't say VM),  so I won't get any extra information there.
    2) The biggest issue is the "get interface for NFS" piece of code in ReadState runs even before the VM has been booted and has not completed its build.   (Take a look at action.rb)

If you require to mount a shared resource, it will be much more reliable to do it from a reliable source. (like your centralized NFS server, not your local PC)

**Comment by clong** [comment] 2019-04-26 07:47
Er sorry, I may not be explaining the issue clearly. This issue exists whether SMB/NFS is being used or not. The issue exists when Vagrant or the plugin decides which interface on the guest it's going to use for provisioning over the communicator (SSH/WinRM). If I'm reading the code correctly, I think that interface/address gets determined here: https://github.com/josenk/vagrant-vmware-esxi/blob/master/lib/vagrant-vmware-esxi/action/read_ssh_info.rb#L56-L79

I agree though, I can't think of any non-hacky way to determine which is the "right" or "best" address to have vagrant attempt to connect to. The problem arises when it tries to connect to an address that it doesn't have a route or network connectivity to, causing it to just timeout and fail. 

Feel free to close this issue if you think it's reached a dead end - I thought it might be worth mentioning in case you had any ideas for a workaround, but I think the challenge here is clear.

**Comment by josenk** [comment] 2019-04-28 02:11
OK, now I understand which IP you're looking for...  The IP of the newly created guest.

Yes, that can be difficult when you have multiple interfaces too...   The thing to remember is that vmware tools / open-vm-tools is providing the IP.   I just read what it reports.   As you can see in the code, I also use two different methods to get the IP.  If vmware tools or open-vm-tools provides the "wrong" IP, then there's not much I can do about that...

The fix for this problem is to install the guest using 1 virtual network interface and make sure vmware tools or open-vm-tools is installed.

**Closed by josenk** 2019-04-28 02:11 UTC

**Comment by 773-process-312** [comment] 2020-06-08 17:13
Can I use this on my esxi host
